repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [ -over=15 ]
      - id: validate-toml
      - id: golangci-lint
      - id: go-critic
      - id: go-mod-tidy
